spring:
  application:
    name: eatgo-customer
  datasource:
    url: ${H2_REAL_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: ${CUSTOMER_PORT}

jwt:
  secret: 12345678123456781234567812345678
---
spring:
  datasource:
    url: ${H2_TEST_URL}
  config:
    activate:
      on-profile: test
