spring:
  main:
    allow-circular-references: true
  application:
    name: eatgo-login
  datasource:
    url: ${H2_REAL_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${LOGIN_PORT}

logging:
  level:
    org.hibernate:
      sql: debug
      orm.jdbc.bind: TRACE

jwt:
  secret: ${JWT_SECRET}
---
spring:
  datasource:
    url: ${H2_TEST_URL}
  config:
    activate:
      on-profile: test
