spring:
  application:
    name: eatgo-admin
  datasource:
    url: ${H2_REAL_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${ADMIN_PORT}

logging:
  level:
    org.hibernate:
      sql: debug
      orm.jdbc.bind: TRACE
---
spring:
  datasource:
    url: ${H2_TEST_URL}
  config:
    activate:
      on-profile: test